# syntax=docker/dockerfile:1@sha256:4c68376a702446fc3c79af22de146a148bc3367e73c25a5803d453b6b3f722fb
# check=skip=SecretsUsedInArgOrEnv #Ignoring due to ENV values not containing any value by default

# Use a lightweight Python image
FROM python:3.13.2@sha256:bc336add24c507d3a11b68a08fe694877faae3eab2d0e18b0653097f1a0db9f3

LABEL maintainer="Cuan Leo (github.com/data-tangles)"

# Set the working directory
WORKDIR /app

# Copy application files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variables inside the container
ENV CLIENT_ID=""
ENV CLIENT_SECRET=""
ENV SECRET_KEY=""
ENV WORKERS=4

# Expose the port Flask runs on
EXPOSE 5000

# Start the application
CMD ["sh", "-c", "gunicorn -w ${WORKERS:-4} -b 0.0.0.0:5000 app:app"]