# syntax=docker/dockerfile:1@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32
# check=skip=SecretsUsedInArgOrEnv #Ignoring due to ENV values not containing any value by default

# Use a lightweight Python image
FROM python:3.13.2@sha256:0293f851d58c726748c9f5d7dca65528ac2d38887b18a48e5689f6c59ef77ea9

LABEL maintainer="Cuan Leo (github.com/data-tangles)"

# Set the working directory
WORKDIR /app

# Copy application files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variables inside the container
ENV CLIENT_ID=""
ENV CLIENT_SECRET=""
ENV SECRET_KEY=""
ENV WORKERS=4

# Expose the port Flask runs on
EXPOSE 5000

# Start the application
CMD ["sh", "-c", "gunicorn -w ${WORKERS:-4} -b 0.0.0.0:5000 app:app"]